using System.Text.Json.Serialization;
using ToSic.Cre8magic.Oqtane.TemplateGenerator.Models;

// <auto-generated/>
[JsonSerializable(typeof(TemplateGeneratorConfig))]
[JsonSourceGenerationOptions(WriteIndented = true)]
public partial class TemplateGeneratorConfigJsonContext : JsonSerializerContext
{
}
