using System.Text.Json;
using System.Text.Json.Serialization;
using ToSic.Cre8magic.Oqtane.Transformer.Models;

// <auto-generated/>
[JsonSerializable(typeof(TransformerConfig))]
[JsonSourceGenerationOptions(WriteIndented = true, AllowTrailingCommas = true, ReadCommentHandling = JsonCommentHandling.Skip)]
public partial class TransformerConfigJsonContext : JsonSerializerContext
{
}
